### ISSUE TITLE
Runtime error in gentx sign 

### ISSUE THREAD

**Issue by mnugumanova** [cosmos/game-of-stakes#195]
Steps:
1: create a new transaction via 
`gaiad gentx   --amount 10000STAKE   --commission-rate "0.10"   --commission-max-rate "1.00"   --commission-max-change-rate "0.01"   --pubkey $(gaiad tendermint show-validator)    --name mira`
2. Edit memo field and save the changes into the same file that was generated by step1
3. run `gaiacli tx sign gentx-fbe59b2d984e20c78c943c0ae46a251fc3e193a8.json --name mira`

Expected:
 there should be a new transaction with signed changes

Actual:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc21d61]`

P.S. Tried to go through `gaiacli tx stake create-validator` flow and `gaiacli tx sign unsignedValTx.json --from=<validator_key_name> > signedValTx.json` and got the same result

**Comment by zmanian** [comment]
Could you post the entire stack trace?

**Comment by mnugumanova** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc21d61]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/client/context.CLIContext.GetAccountNumber(0xc420154690, 0xc4209a26b0, 0x12a3840, 0xc4209a0540, 0x128d9e0, 0xc42000e018, 0x0, 0xe6c12c, 0x15, 0x0, ...)
	/root/go/src/github.com/cosmos/cosmos-sdk/client/context/query.go:101 +0xe1
github.com/cosmos/cosmos-sdk/client/utils.SignStdTx(0x0, 0x0, 0x0, 0x30d40, 0x3ff0000000000000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/cosmos/cosmos-sdk/client/utils/utils.go:132 +0x53a
github.com/cosmos/cosmos-sdk/x/auth/client/cli.makeSignCmd.func1(0xc42094cc80, 0xc420896c80, 0x1, 0x4, 0x0, 0x0)
	/root/go/src/github.com/cosmos/cosmos-sdk/x/auth/client/cli/sign.go:87 +0x497
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc42094cc80, 0xc420896c40, 0x4, 0x4, 0xc42094cc80, 0xc420896c40)
	/root/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200c6a00, 0x6, 0xc42090fd60, 0x0)
	/root/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200c6a00, 0xe5e0f4, 0x6)
	/root/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc4200c6a00, 0x121ce48, 0x0, 0xc4201d9aa0)
	/root/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/root/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiacli/main.go:103 +0x53f
