### ISSUE TITLE
Testnet stability before GoS launch

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/game-of-stakes#235]
We, as the validators, have been involved in testnet deployments for a long time, some of us since December 2017. Even though we really want to see Game of Stakes launching as soon as possible, we also want to have a reliable and fair game. The current process of announcing a starting date/time and then postponing is not only extremely time-consuming but also very stressful. 

We don’t have a stable version of the software and the only reason why we caught the last bug (liveness bug in Tendermint) is that a bunch of us have started to set up their own community testnets, irrespective of Tendermint. Given the special status of Game of Stakes for many people in the community (both in terms of signalling and monetary rewards), we would rather see a fair game that doesn’t immediately break due to some simple bug. Instead, we would like to have a testnet that actually test a validator’s preparedness. 

We would like to propose that we only launch GoS once we have a testnet that runs for at least a week without any major bugs. A later launch of GoS is better than a botched one. This will enforce the practice that validators should be conservative in the software that we are running.

**Comment by zmanian** [comment]
Please thumbs up/thumbs down / comment on your point of view.

**Comment by fkbenjamin** [comment]
I was talking to @adrianbrink recently and 100% agree with the proposal above. I think this will in the end benefit the whole experience of the Game of Stakes.

**Comment by mdyring** [comment]
I am all for delaying, until we've had a stable testnet for a meaningful period of time.

It would be a big disappointment for everybody, validators, Tendermint/Cosmos team and "passive" fundraise participants alike, if GoS died due to lack of prior testing.

We have to keep an eye on the long term goal here, which is launch of a stable and production ready network.

**Comment by kwunyeung** [comment]
I agree to delay the GoS. It will be better for validators to understand well and test the latest software. It also give enough time to Tendermint team to solve some issues we found out in the last couple community testnets. The stop of genki-3000 did meant there are bugs which would make GoS failure.

**Comment by iammelea** [comment]
from my point of view @adrianbrink have totally my support in his words. I agree to delay the GoS because imo is the best choice for a successful GoS.

**Comment by aaronhenshaw** [comment]
I agree with this 100%. We are super excited for Game of Stakes and would like to have more conviction that the software is reliable. A week of a community or cosmos team led testnet without new bugs or software releases feels like enough time to me.

I would just want to reiterate that any software releases should really reset the clock and a new test net should be spun up :) 

 Thanks for putting this together @adrianbrink and everyone else involved!

**Comment by chris-remus** [comment]
As one of the validators in the group since day 1, I agree! This approach will move the process in a a beneficial and healthy direction for all involved. Thanks to @adrianbrink for the clear and concise proposal.

**Comment by nodebreaker-carl** [comment]
I agree! This should have an understanding of the future of Cosmos.
I think stable tests and the gos based on them are very important.

**Comment by wimel** [comment]
I agree with delaying GoS.
A lot of time spent learning how it works and how to configure the nodes to continue delaying and delaying just hours before, it's time to continue learning. 
As well commented above, it would be good to announce with time to be prepared, I understand that setting specific dates is very difficult, but it would be good to plan in advance the details of GoS.
Thank you for the sincerity and clarification.
The project is good and big, we will continue to support the project and contribute in whatever way we can.

**Comment by gin** [comment]
👍
🐞📉
⛰📈

**Comment by clawmvp** [comment]
i also agree.

**Comment by timogilvie** [comment]
100% agree

**Comment by phonikg** [comment]
I don't think anyone wins here by rushing things.

**Comment by kidinamoto01** [comment]
I recalled the original plan was to have a stable testnet for a week before the start of GoS, so postponing now makes sense.

**Comment by bunghi** [comment]
+1 
I also agree. ;)

**Comment by plzcallmehan** [comment]
I agree! aye!
