### ISSUE TITLE
ConsensusParams.BlockSize.MaxBytes causing mempool tx failure

### ISSUE THREAD

**Issue by jaekwon** [cosmos/game-of-stakes#242]
ConsensusParams.BlockSize.MaxBytes causing mempool tx failure.
Seeing reports of:
```
ERROR: broadcast_tx_commit: Response error: RPC error -32603 - Internal error: Error on broadcastTxCommit: Tx size (including amino overhead) is too big: 197, max: 182
```
The genesis MaxBytes, which was intended to be a MaxDataBytes, was 50,000.
Now with 199 validators at block 1511, we have already reached capacity.

Sol_1:  One solution is to update the code so that rather than MaxBytes we have MaxDataBytes, and for validator sets to not affect this data cap, because that is least surprising.  Arguably, it doesn't make sense to make the user consider a max cap block size as in Bitcoin, in the case where there is a variable number of validators, and for the data cap to increase or decrease in relative to the number of validators.  These concerns are ideally kept separate, so that you can set the max data tx size independent of the max validators.  When receiving a block proposal, the validators can reject blocks that are significantly larger than expected, e.g. we could expect block size of MaxDataBytes+500k, which gives sufficient extra room for validators etc, and then run the validation checks again after having received it.  -- this is what I tried implementing in https://github.com/tendermint/tendermint/pull/3045/files .  It isn't difficult to finish, though we probably shouldn't be deploying this tomorrow when the alternative option is easier, to bump the MaxBytes to 150k.

Sol_2: Or, we can have MaxBytes AND MaxDataBytes.  But we shouldn't couple these together so much.  We should make them more "loose" so that we can still limit MaxDataBytes to be small (50k) even though MaxBytes is large (e.g. 1MB).

A soft fork upgrade isn't possible because the ConsensusState MaxBytes option is enforced at the consensus layer when reconstructing the block from the proposer's ProposalBlockParts.

---------

(Optionality A) We restart the chain with a larger block size, 150k (3x) seems pretty reasonable, and let the Tendermint team address the above concerns in due time.  Or, we let the community do it.

(Optionality B) We export from the block # where there were 199 validators (some time before block \#1500 I think), which is when the block size became the limiting factor for even a single transaction.  Or, we restart genesis from scratch, since it hasn't been 24 hours anyways.

**Comment by kauchy** [comment]
after delete PreCheckAminoMaxBytes in tendermint,then delegate transaction works fine.because it only use in Mempool.CheckTx.

but need to wait self proposer
