### ISSUE TITLE
Cannot verify genesis file for game_of_stakes_2

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/game-of-stakes#255]
I exported the genesis file following [these]() instructions. Then I modified three keys `genesis_time`, `chain_id`, and `max_bytes`.

```json
"genesis_time": "2018-12-21T15:00:00.000000Z",
  "chain_id": "game_of_stakes_2",
  "consensus_params": {
    "block_size": {
      "max_bytes": "150000",
      "max_gas": "1500000"
    },
```

Afterwards I sorted the files and compared the hashes. They don't match which mean I cannot verify that no one modified them in any other way.

```
adrian@gos-public-sentry-1:~/.gaiad/config$ sha512sum sorted_exported_genesis.json
6688fb37a0892a9b2aed362cf57e1b2ceb581c76dacf9d9c882e51b0c629aa81216de3c2296e24fa4123100459494f37e8061299f9d9cf7f22c239537d78d25d  sorted_exported_genesis.json

adrian@gos-public-sentry-1:~/.gaiad/config$ sha512sum sorted_proposed_genesis.json
5c65d6b6196067df5d9d3716ef7fb862a6c10747461695cfa379f85c9ce11520904aafe4c9feea09f7f355e33468dc711cc61d5e2c4b61f7738980091c7ebe9e  sorted_proposed_genesis.json
```

Are there modifications between the exported genesis file and those three keys mentioned above that happened?

**Comment by fkbenjamin** [comment]
The unbonding_height was changed since this caused the crash yesterday. [Here](https://github.com/cosmos/game-of-stakes/commit/c4feb823b8f38288e68429b820e1c58404aa4c36) is the commit.
