### ISSUE TITLE
memo field exposes sensitive info

### ISSUE THREAD

**Issue by awrelll** [cosmos/game-of-stakes#51]
when generating the genesis tx, the `memo` field exposes the validators IP and ID, both should be kept private.

**Comment by Slamper** [comment]
You cannot modify the memo field. That would invalidate your gentx.

You can however generate the gentx using `./gaiacli tx stake create-validator --genesis-format` and `gaiacli tx sign`.
Then you can change the memo.

**Comment by chris-remus** [comment]
Please say more on that ☝️ @Slamper

**Comment by Slamper** [comment]
You can take a look at the cli help of both of these commands to see how exactly they are used.

When you have generated your gentx you can check it using our gentx tool :)

**Comment by wimel** [comment]
ok thanks @Slamper, but for example my machine is virtualized and doesn't show a public IP, I haven't modified it, but it shows the IP as an internal network.
Can this cause a problem?

**Comment by Slamper** [comment]
@wimel No that's not a problem as the memo field is not used at the moment as far as I know.
